### ISSUE TITLE
Native has an old dependency on NuGet package Microsoft.ServiceFabric.Services.Remoting

### ISSUE THREAD

**Issue by PooSham** [microsoft/ApplicationInsights-ServiceFabric#109]
`Microsoft.ApplicationInsights.ServiceFabric.Native` references `Microsoft.ServiceFabric.Services.Remoting` version `3.3.664`, but the newest is `4.0.464`. 

Please update this package, as it causes many NuGet conflicts with other packages. While it is fixable by referencing `Microsoft.ServiceFabric.Services.Remoting` directly, it would be nice if you could update your references to not bug the users of this library.

**Comment by yantang-msft** [comment]
@PooSham are you see the version conflicts of ```Microsoft.ServiceFabric.Diagnostics.Internal```? This has been the known and common issue of our package, and the real problem is ```Microsoft.ServiceFabric.Services.Remoting``` locked their version on  ```Microsoft.ServiceFabric.Diagnostics.Internal```. See more comments here:
https://github.com/microsoft/ApplicationInsights-ServiceFabric/issues/82#issuecomment-421148430, https://github.com/microsoft/ApplicationInsights-ServiceFabric/issues/79#issuecomment-423682672

Even if updated our dependency version to ```4.0.464```, next time you upgrade ```Microsoft.ServiceFabric.Services.Remoting``` version, the same issue will still come up. So we suggest that you just reference ```Microsoft.ServiceFabric.Services.Remoting```
