### ISSUE TITLE
Microsoft.ApplicationInsights.EventSourceListener for .net 4.5.1

### ISSUE THREAD

**Issue by WillTartak** [Microsoft/ApplicationInsights-ServiceFabric#12]
We are in the process of upgrading some of our services and would like to use the new ServiceFabric ApplicationInsights integration. We are currently running .net framework 4.5.1. Is there any way we can get Microsoft.ApplicationInsights.EventSourceListener to run on .net 4.5.1?

If this is the wrong place to publish this please point me in the right direction.

**Comment by nizarq** [comment]
EventsourceListener has nothing to do with this repository but I think @karolz-ms may be able to answer this.

**Comment by karolz-ms** [comment]
@WillTartak  No, sorry. EventSourceListener requires APIs that have been added to .NET Fx only in 4.6 (and core 1.0)

FWIIW .NET 4.6.1 has been the default framework for Azure VMs since October last year. It is a very safe bet and has a lot of bug fixes and improvements. Any specific reason to stay on 4.5.1?

**Comment by WillTartak** [comment]
@karolz-ms I'm a consultant helping out with implementation. The call for Fx version is beyond my point of influence. I will let the appropriate folks know the issue. Thanks!

**Comment by WillTartak** [comment]
@karolz-ms what is the appropriate repo for any further questions on this component and its brothers?

**Comment by karolz-ms** [comment]
@WillTartak https://github.com/Microsoft/applicationInsights-dotnet-logging/
