### ISSUE TITLE
Could you please show project examples?

### ISSUE THREAD

**Issue by artsai** [Microsoft/ApplicationInsights-ServiceFabric#37]
Could you please show examples for Stateless WebApi and Remoting? 
So with this AI Sdk, I don't have to setup ServiceEventSource anymore, and just create TelemetryClient singleton instead, correct?

**Comment by nizarq** [comment]
Readme is your friend here. [Set the context](https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/develop/README.md#net-framework-1) from your service entry points. For trace correlation using service remoting, [make sure you follow this](https://github.com/Microsoft/ApplicationInsights-ServiceFabric/blob/develop/README.md#trace-correlation-with-service-remoting).

Finally, you could play with the [OneApp](https://github.com/qubitron/service-fabric-dotnet-getting-started) from my colleague @qubitron 's repo. There are enough examples there to see this all in action.

And yes, you can use the TelemetryClient for all your telemetry needs instead of ServiceEventSource, if you want to target an application insights resource as your telemetry store (which is what we recommend).
