### ISSUE TITLE
CorrelationServiceRemotingClient and listener don't resolve method name at all causing telemetry operation name being always 0.

### ISSUE THREAD

**Issue by n3gwave** [Microsoft/ApplicationInsights-ServiceFabric#71]
Hi, there is a bug in resolving correct operation name both in client and listener. Operation name should be a calling method name but it's always 0 instead. The reason for that is invalid type name string in ctor in class ServiceRemotingMessageHeadersExtensions. Line 24.

`Type actorMessageHeadersType = typeof(ActorMethodDispatcherBase).Assembly.GetType("Microsoft.ServiceFabric.Actors.Remoting.ActorMessageHeaders");`

Turns out ActorMessageHeaders class is in different namespace **Microsoft.ServiceFabric.Actors.Remoting.V1**

https://github.com/Microsoft/service-fabric-services-and-actors-dotnet/blob/97dff2cc2efc022c69363073881d6a92e8c5462c/src/Microsoft.ServiceFabric.Actors/Remoting/V1/ActorMessageHeaders.cs

Adding 'V1' does the trick.

**Comment by yantang-msft** [comment]
@n3gwave Thank you for reporting this. This is probably a "breaking" change when Service Remoting V2 is added (well, it's internal class, so not a real breaking change for Service Fabric).
Before the fix is released (probably in a week or two), you can try using Servcie Remoting V2 if it's an option for you.

**Comment by yantang-msft** [comment]
Fixed in PR https://github.com/Microsoft/ApplicationInsights-ServiceFabric/pull/72.
